/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/APIPage': RouteRecordInfo<
      '/APIPage',
      '/APIPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ChangelogPage': RouteRecordInfo<
      '/ChangelogPage',
      '/ChangelogPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComponentLabelPage': RouteRecordInfo<
      '/ComponentLabelPage',
      '/ComponentLabelPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComponentThemePickerPage': RouteRecordInfo<
      '/ComponentThemePickerPage',
      '/ComponentThemePickerPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComponentTimePage': RouteRecordInfo<
      '/ComponentTimePage',
      '/ComponentTimePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DefaultPropsPage': RouteRecordInfo<
      '/DefaultPropsPage',
      '/DefaultPropsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/EditThemePage': RouteRecordInfo<
      '/EditThemePage',
      '/EditThemePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/Error404Page': RouteRecordInfo<
      '/errors/Error404Page',
      '/errors/Error404Page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HelpQuasarPage': RouteRecordInfo<
      '/HelpQuasarPage',
      '/HelpQuasarPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomePage': RouteRecordInfo<
      '/HomePage',
      '/HomePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/InstallPage': RouteRecordInfo<
      '/InstallPage',
      '/InstallPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/KitchenSinkPage': RouteRecordInfo<
      '/KitchenSinkPage',
      '/KitchenSinkPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/UtilCssClassesPage': RouteRecordInfo<
      '/UtilCssClassesPage',
      '/UtilCssClassesPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/UtilSnippetsPage': RouteRecordInfo<
      '/UtilSnippetsPage',
      '/UtilSnippetsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/APIPage.vue': {
      routes:
        | '/APIPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ChangelogPage.vue': {
      routes:
        | '/ChangelogPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComponentLabelPage.vue': {
      routes:
        | '/ComponentLabelPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComponentThemePickerPage.vue': {
      routes:
        | '/ComponentThemePickerPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComponentTimePage.vue': {
      routes:
        | '/ComponentTimePage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/DefaultPropsPage.vue': {
      routes:
        | '/DefaultPropsPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/EditThemePage.vue': {
      routes:
        | '/EditThemePage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/Error404Page.vue': {
      routes:
        | '/errors/Error404Page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/HelpQuasarPage.vue': {
      routes:
        | '/HelpQuasarPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/HomePage.vue': {
      routes:
        | '/HomePage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/InstallPage.vue': {
      routes:
        | '/InstallPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/KitchenSinkPage.vue': {
      routes:
        | '/KitchenSinkPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/UtilCssClassesPage.vue': {
      routes:
        | '/UtilCssClassesPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/UtilSnippetsPage.vue': {
      routes:
        | '/UtilSnippetsPage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
