name: Build and Deploy Playground

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.7.0'

      - name: Install workspace dependencies
        run: |
          pnpm install

      - name: Prepack extension
        run: |
          cd ae
          pnpm run prepack

      - name: Install dependencies and build playground
        run: |
          cd playground
          pnpm exec quasar b

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: playground/dist/spa

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4